### PR TITLE
changed usage of time in vision.py to rospy.rate

### LINKED ISSUE #216: Vision: Use rospy.rate
## Describe the solution you'd like
Instead of looping with time, we could use rospy.rate as can be seen in the localization.
This applies to the `vision.py` as well as `dynamic_color_space.py`.

### PR DESCRIPTION
**Pull request by hendrikbrandt**
## Proposed changes
replaced time with rospy.rate and rate.sleep in vision.py for both the main loop and the dynamic reconfigure callback

## Related issues
Closes #216 

## Necessary checks
- [x] Run `catkin build`
~- [ ] Write documentation~
~- [ ] Create issues for future work~
- [x] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

### CODE REVIEW

**Comment by jaagut** [comment]
This should wait until #219 is merged.

**Comment by jaagut** [comment]
#219 is done. This could continue now.

**Comment by Flova** [comment]
Please resolve the merge conflicts first.

**Comment by jaagut** [comment]
@Flova done. The question is, what do we do with the🎶 dynamic color lookuptable node?

**Review by jaagut — APPROVED** [review]

**Comment by jaagut** [comment]
Tested and seems to work

**Review by Flova — APPROVED** [review]

**Pull request merged**
