### PR TITLE
remove field boundary detection from yoeo vision

### PR DESCRIPTION
**Pull request by phinik**
## Proposed changes
Remove the field boundary detection from yoeo vision

## Related issues
Solves https://github.com/bit-bots/bitbots_vision/issues/348

## Necessary checks
- [ ] Test on your machine
- [ ] Test on the robot

### CODE REVIEW

**Comment by jaagut** [comment]
The original goal of the issue #348 was to remove the complete handling and detection of field boundaries, as they are not used and needed anymore. Thus, reducing code complexity in the vision node.
Another thing, but rather part of general cleanup is the removal of the not-YOEO vision.

**Comment by phinik** [comment]
> The original goal of the issue #348 was to remove the complete handling and detection of field boundaries, as they are not used and needed anymore. Thus, reducing code complexity in the vision node. Another thing, but rather part of general cleanup is the removal of the not-YOEO vision.

I would prefer to have a dedicated issue + PR for removing the legacy vision. Removing the field boundaries alone would most likely break the legacy vision, and there is no point in untangling it from the legacy vision if the latter is to be removed anyway in a subsequent PR.

**Comment by jaagut** [comment]
In favor of #351, this is obsolete.

**Comment by phinik** [comment]
I actually meant we take this PR to remove the field boundaries from the YOEO vision and a second PR to remove the legacy vision in one go.

**Comment by phinik** [comment]
Ready to review

**Review by jaagut — APPROVED** [review]
Tested it and seems to work!

**Pull request merged**
