### PR TITLE
Use yolo intersections

### PR DESCRIPTION
**Pull request by Flova**
## Proposed changes
Publish and visualize the line intersections from YOLO
This builds on #279 

## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

### CODE REVIEW

**Comment by SammyRamone** [comment]
@Flova does this still make sense? otherwise please delete the branch

**Comment by Flova** [comment]
This makes sense and we want to add it in the future, but for now I have higher prior todos

**Comment by jaagut** [comment]
This is outdated, and we don't plan to use it anytime soon.

**Comment by jaagut** [comment]
This is outdated, and we don't plan to use it anytime soon.

**Pull request closed without merging**
